[package]
version = "0.1.0"
name = "regex-script"
edition = "2021"

[dependencies]
sphinx-core = { path = "../../../core" }
sphinx-sdk = { path = "../../../sdk" }

[build-dependencies]
sphinx-helper = { path = "../../../helper" }
