[workspace]
[package]
version = "0.1.0"
name = "rsa-script"
edition = "2021"

[dependencies]
rsa = "0.6"
wp1-sdk = { path = "../../../sdk" }

[build-dependencies]
wp1-helper = { path = "../../../helper" }
