[package]
version = "0.1.0"
name = "bls12381-pairing-script"
edition = "2021"

[dependencies]
bincode = "1.3.3"
sphinx-sdk = { path = "../../../sdk" }

[build-dependencies]
sphinx-helper = { path = "../../../helper" }
