[package]
version = "0.1.0"
name = "sum-script"
edition = "2021"

default-run = "sum-script"

[dependencies]
bincode = "1.3.3"
sphinx-sdk = { path = "../../../sdk" }

[build-dependencies]
sphinx-helper = { path = "../../../helper" }

[[bin]]
name = "sum-script"
path = "src/main.rs"
